-- Likes table
CREATE TABLE likes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    user_fid BIGINT NOT NULL
);
ALTER TABLE likes ADD CONSTRAINT unique_like UNIQUE (article_id, user_fid);
CREATE INDEX idx_likes_article_id ON likes(article_id);

-- Flags table
CREATE TABLE flags (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    article_id UUID NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
    user_fid BIGINT NOT NULL
);
ALTER TABLE flags ADD CONSTRAINT unique_flag UNIQUE (article_id, user_fid);
CREATE INDEX idx_flags_article_id ON flags(article_id);

-- Point logs table for auditing
CREATE TABLE point_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_fid BIGINT NOT NULL,
    points_awarded INT NOT NULL,
    reason TEXT,
    related_article_id UUID,
    related_user_fid BIGINT
);
CREATE INDEX idx_point_logs_user_fid ON point_logs(user_fid);
